import Head from 'next/head'
import Image from 'next/image'
import Body from './components/Body'
import Header from './components/Header'
import {BiBookBookmark} from 'react-icons/bi'

import Grid from '@mui/material/Grid';
import styles from '../styles/Home.module.css'

export default function Home() {
  const repos = ['REPO1REPO1REPO1REPO1', 'REPO2', 'REPO3', 'REPO4'];

  return (
    <>
    <Header />
    <div className={styles.container}>
      <Grid container spacing={1}>
        <Grid item xs={3} className={styles.sidebar}>
          <div className={styles['sidebar-title-container']}>
            <p className={styles['sidebar-title']}>Repositories</p>
          </div>
          <div className='repo-holder'>
          {
            repos.map((repo, index) => {
              return (
                <div key={index}> 
                <Grid container >
                    <Grid item xs={1}>
                      <BiBookBookmark size={30} />
                      </Grid>
                    <Grid item xs={11}>
                      <div onClick={(e)=>{}} className={styles['repo-name']}>{repo}</div>
                    </Grid>
                </Grid>
                </div>
              )
            })
          }
          </div>
        </Grid>
        <Grid item xs={9} className={styles.dashboard}>
            <p>
              aa
            </p>
        </Grid>        
      </Grid>
    </div>
    </>

  )
}


    {/*<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> 
    </div>*/}