import { useState, useEffect } from 'react';
import Body from './components/Body'
import Header from './components/Header'
import axios from 'axios';

export default function Home() {
  const [repos, setRepos] = useState([]);
  const [loadingRepos, setLoadingRepos] = useState(true)
  const [selectedRepo, setSelectedRepo] = useState({})
  const [selectedRepoName, setSelectedRepoName] = useState('')

  const handleSelectedRepo = (e) => {
    setSelectedRepoName(e.target.innerText)
  }

  useEffect(()=>{
    if(selectedRepoName === ""){
      return 
    }

    axios.get(`api/getRepoInfo?repoName=${selectedRepoName}`)
    .then(response=>{
      setSelectedRepo(response.data)
    })
    .catch(error=>{
      console.log(error)
    })

  },[selectedRepoName])
  
  useEffect(() => { 
    setLoadingRepos(false)
    axios.get('api/getUserInfo')
      .then(res => {
        console.log('res.data',res.data.repos)
        setLoadingRepos(false)
        setRepos(res.data.repos);
        setSelectedRepoName(res.data.repos[0].name)
      })
      .catch(err=>{
        console.log(err)
        setLoadingRepos(false)
      })
    
  },[])


  return (
    <>
    <Header />
    <Body handleSelectedRepo={handleSelectedRepo} selectedRepo={selectedRepo} repos={repos} loadingRepos={loadingRepos} />
    </>

  )
}


    {/*<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> 
    </div>*/}